markdown: redcarpet
highlighter: pygments
rdiscount:
  extensions: [smart]
timezone: DE


permalink: /:title


destination: _site
base_url: "http://wikimatze.de"

author: Matthias Günther


exclude:
  - _drafts
  - Gemfile
  - Gemfile.lock
  - plugins
  - knowledge.md
  - Rakefile
  - bin


include:
  - .htaccess


# yaml default setup
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
  -
    scope:
      path: "" # empty string for all files
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "books" # empty string for all files
    values:
      layout: "reading"


# page stats
build: 5-23-2014
images: 42
htmlpages: 68
links: 460


tag_page_layout: tag_page
tag_page_dir: tag


# github stats
zimki: 2012-07-26
sweetie: 2012-07-26


# bitbucket stats
pmwiki-dropcaps-recipe: 2013-01-20
pmwiki-headlineimage-recipe: 2013-01-20
pmwiki-linkicons-recipe: 2013-01-20
pmwiki-syntaxlove-recipe: 2013-01-20
pmwiki-twitter-recipe: 2012-07-27
css-hacks: 2013-02-04
haskell-lang: 2013-01-26
go-lang: 2013-01-26
rails-sample-app: 2013-01-26
ruby-scripts: 2013-01-26
vocabularly: 2013-01-26
styles: 2013-01-26
presentations: 2014-02-18
windows setup: 2013-01-27
iso25: 2012-11-19
vim-autocomplpop: 2013-07-17
